### ISSUE TITLE
FTB Chunks Dependency? 

### ISSUE THREAD

**Issue by RealR053** [Patbox/UniversalShops#29]
Game crashes for me as soon as I interact with the shop above a chest unless FTB Chunks is installed (1.19.2)

**Comment by Patbox** [comment]
It does not depend on that mod, check logs

**Comment by RealR053** [comment]
Yeah I am not entirely sure why the Better MC1 modpack I am playing is trying to retrieve the FTB Chunks API whenever I interact with the shop menu, that's probably why it is crashing.

[13/07/2024 20:38:12 pm] ---- Minecraft Crash Report ----
[13/07/2024 20:38:12 pm] // Daisy, daisy...
[13/07/2024 20:38:12 pm] 
[13/07/2024 20:38:12 pm] Time: 2024-07-13 20:38:12
[13/07/2024 20:38:12 pm] Description: Ticking block entity
[13/07/2024 20:38:12 pm] 
[13/07/2024 20:38:12 pm] java.lang.NoClassDefFoundError: dev/ftb/mods/ftbchunks/data/FTBChunksAPI
[13/07/2024 20:38:12 pm] 	at dev.ftb.mods.ftbxmodcompat.fabric.ftbchunks.commonprot.FTBChunksProtectionProvider.canInteractBlock(FTBChunksProtectionProvider.java:115)
[13/07/2024 20:38:12 pm] 	at eu.pb4.common.protection.impl.ProtectionImpl.canInteractBlock(ProtectionImpl.java:70)
[13/07/2024 20:38:12 pm] 	at eu.pb4.common.protection.api.CommonProtection.canInteractBlock(CommonProtection.java:44)
[13/07/2024 20:38:12 pm] 	at eu.pb4.universalshops.registry.TradeShopBlockEntity.getContainer(TradeShopBlockEntity.java:215)
[13/07/2024 20:38:12 pm] 	at eu.pb4.universalshops.trade.StockHandler$SingleItem.transfer(StockHandler.java:205)
[13/07/2024 20:38:12 pm] 	at eu.pb4.universalshops.trade.StockHandler$SingleItem.getMaxAmount(StockHandler.java:197)
[13/07/2024 20:38:12 pm] 	at eu.pb4.universalshops.registry.TradeShopBlockEntity.tickHolo(TradeShopBlockEntity.java:130)
[13/07/2024 20:38:12 pm] 	at eu.pb4.universalshops.registry.TradeShopBlockEntity.tick(TradeShopBlockEntity.java:99)
[13/07/2024 20:38:12 pm] 	at eu.pb4.universalshops.registry.TradeShopBlock.tick(TradeShopBlock.java:122)
[13/07/2024 20:38:12 pm] 	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:660)
[13/07/2024 20:38:12 pm] 	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:714)
[13/07/2024 20:38:12 pm] 	at net.minecraft.class_1937.method_18471(class_1937.java:456)
[13/07/2024 20:38:12 pm] 	at net.minecraft.class_3218.method_18765(class_3218.java:376)
[13/07/2024 20:38:12 pm] 	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
[13/07/2024 20:38:12 pm] 	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
[13/07/2024 20:38:12 pm] 	at net.minecraft.class_1132.method_3748(class_1132.java:98)
[13/07/2024 20:38:12 pm] 	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
[13/07/2024 20:38:12 pm] 	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
[13/07/2024 20:38:12 pm] 	at java.base/java.lang.Thread.run(Thread.java:833)
[13/07/2024 20:38:12 pm] Caused by: java.lang.ClassNotFoundException: dev.ftb.mods.ftbchunks.data.FTBChunksAPI
[13/07/2024 20:38:12 pm] 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
[13/07/2024 20:38:12 pm] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
[13/07/2024 20:38:12 pm] 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
[13/07/2024 20:38:12 pm] 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
[13/07/2024 20:38:12 pm] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
[13/07/2024 20:38:12 pm] 	... 19 more
[13/07/2024 20:38:12 pm] 
[13/07/2024 20:38:12 pm] 
[13/07/2024 20:38:12 pm] A detailed walkthrough of the error, its code path and all known details is as follows:
[13/07/2024 20:38:12 pm] ---------------------------------------------------------------------------------------
[13/07/2024 20:38:12 pm] 
[13/07/2024 20:38:12 pm] -- Head --
[13/07/2024 20:38:12 pm] Thread: Render thread
[13/07/2024 20:38:12 pm] Stacktrace:
[13/07/2024 20:38:12 pm] 	at dev.ftb.mods.ftbxmodcompat.fabric.ftbchunks.commonprot.FTBChunksProtectionProvider.canInteractBlock(FTBChunksProtectionProvider.java:115)
[13/07/2024 20:38:12 pm] 	at eu.pb4.common.protection.impl.ProtectionImpl.canInteractBlock(ProtectionImpl.java:70)
[13/07/2024 20:38:12 pm] 	at eu.pb4.common.protection.api.CommonProtection.canInteractBlock(CommonProtection.java:44)
[13/07/2024 20:38:12 pm] 	at eu.pb4.universalshops.registry.TradeShopBlockEntity.getContainer(TradeShopBlockEntity.java:215)
[13/07/2024 20:38:12 pm] 	at eu.pb4.universalshops.trade.StockHandler$SingleItem.transfer(StockHandler.java:205)
[13/07/2024 20:38:12 pm] 	at eu.pb4.universalshops.trade.StockHandler$SingleItem.getMaxAmount(StockHandler.java:197)
[13/07/2024 20:38:12 pm] 	at eu.pb4.universalshops.registry.TradeShopBlockEntity.tickHolo(TradeShopBlockEntity.java:130)
[13/07/2024 20:38:12 pm] 	at eu.pb4.universalshops.registry.TradeShopBlockEntity.tick(TradeShopBlockEntity.java:99)
[13/07/2024 20:38:12 pm] 	at eu.pb4.universalshops.registry.TradeShopBlock.tick(TradeShopBlock.java:122)
[13/07/2024 20:38:12 pm] 	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:660)
[13/07/2024 20:38:12 pm] 	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:714)
[13/07/2024 20:38:12 pm] 	at net.minecraft.class_1937.method_18471(class_1937.java:456)
[13/07/2024 20:38:12 pm] 	at net.minecraft.class_3218.method_18765(class_3218.java:376)
[13/07/2024 20:38:12 pm] 
[13/07/2024 20:38:12 pm] -- Block entity being ticked --
[13/07/2024 20:38:12 pm] Details:
[13/07/2024 20:38:12 pm] 	Name: universal_shops:trade_block // eu.pb4.universalshops.registry.TradeShopBlockEntity
[13/07/2024 20:38:12 pm] 	Block: Block{universal_shops:trade_block}[attachment=down]
[13/07/2024 20:38:12 pm] 	Block location: World: (3,110,55), Section: (at 3,14,7 in 0,6,3; chunk contains blocks 0,-64,48 to 15,319,63), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
[13/07/2024 20:38:12 pm] 	Block: Block{universal_shops:trade_block}[attachment=down]
[13/07/2024 20:38:12 pm] 	Block location: World: (3,110,55), Section: (at 3,14,7 in 0,6,3; chunk contains blocks 0,-64,48 to 15,319,63), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
[13/07/2024 20:38:12 pm] Stacktrace:
[13/07/2024 20:38:12 pm] 	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:660)
[13/07/2024 20:38:12 pm] 	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:714)
[13/07/2024 20:38:12 pm] 	at net.minecraft.class_1937.method_18471(class_1937.java:456)
[13/07/2024 20:38:12 pm] 	at net.minecraft.class_3218.method_18765(class_3218.java:376)
[13/07/2024 20:38:12 pm] 	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
[13/07/2024 20:38:12 pm] 	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
[13/07/2024 20:38:12 pm] 	at net.minecraft.class_1132.method_3748(class_1132.java:98)
[13/07/2024 20:38:12 pm] 	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
[13/07/2024 20:38:12 pm] 	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
[13/07/2024 20:38:12 pm] 	at java.base/java.lang.Thread.run(Thread.java:833)
[13/07/2024 20:38:12 pm] 
[13/07/2024 20:38:12 pm] -- Affected level --
[13/07/2024 20:38:12 pm] Details:
[13/07/2024 20:38:12 pm] 	All players: 1 total; [class_3222['**MINECRAFTUSERNAME**'/418, l='ServerLevel[New Worldtest]', x=3.64, y=109.00, z=53.42]]
[13/07/2024 20:38:12 pm] 	Chunk stats: 2401
[13/07/2024 20:38:12 pm] 	Level dimension: minecraft:overworld
[13/07/2024 20:38:12 pm] 	Level spawn location: World: (0,103,32), Section: (at 0,7,0 in 0,6,2; chunk contains blocks 0,-64,32 to 15,319,47), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
[13/07/2024 20:38:12 pm] 	Level time: 736 game time, 736 day time
[13/07/2024 20:38:12 pm] 	Level name: New Worldtest
[13/07/2024 20:38:12 pm] 	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
[13/07/2024 20:38:12 pm] 	Level weather: Rain time: 112864 (now: false), thunder time: 61143 (now: false)
[13/07/2024 20:38:12 pm] 	Known server brands: fabric
[13/07/2024 20:38:12 pm] 	Level was modded: true
[13/07/2024 20:38:12 pm] 	Level storage version: 0x04ABD - Anvil
[13/07/2024 20:38:12 pm] Stacktrace:
[13/07/2024 20:38:12 pm] 	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
[13/07/2024 20:38:12 pm] 	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
[13/07/2024 20:38:12 pm] 	at net.minecraft.class_1132.method_3748(class_1132.java:98)
[13/07/2024 20:38:12 pm] 	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
[13/07/2024 20:38:12 pm] 	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
[13/07/2024 20:38:12 pm] 	at java.base/java.lang.Thread.run(Thread.java:833)
[13/07/2024 20:38:12 pm] 
[13/07/2024 20:38:12 pm] -- System Details --
[13/07/2024 20:38:12 pm] Details:
[13/07/2024 20:38:12 pm] 	Minecraft Version: 1.19.2
[13/07/2024 20:38:12 pm] 	Minecraft Version ID: 1.19.2
[13/07/2024 20:38:12 pm] 2024-07-13 20:38:12,463 Netty Local Client IO #0 WARN Error parsing URI **USERSDIR**\assets\log_configs\client-1.12.xml
[13/07/2024 20:38:12 pm] 2024-07-13 20:38:12,480 Netty Local Client IO #0 WARN Unable to register Log4j shutdown hook because JVM is shutting down. Using SimpleLogger
[13/07/2024 20:38:15 pm] Oh no. Minecraft crashed. Please check the logs for any errors and provide these logs when asking for support.
[13/07/2024 20:38:15 pm] Checking for updated files!
[13/07/2024 20:38:15 pm] Checking for updates to CurseForge instances

**Comment by Patbox** [comment]
It's a bug caused by ftbxmodcompat blindly assuming ftb chunks is present for protection checks while it isn't. Report it to ftb people

**Comment by RealR053** [comment]
Okay thanks very much for the quick response! Apologies for the confusion.
